# pre-commit hooks configuration
repos:

  # Local repository with custom hooks
  - repo: local
    hooks:
      - id: check-commit-size
        name: check-commit-size
        entry: python -m pre_commit_hooks.check_commit_size
        language: python
        types: [text]
        args: [--max-additions=1000, --exclude=tests/**]
        pass_filenames: false
        description: Check commit size limits (additions and deletions)

  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v6.0.0
      hooks:
      -   id: trailing-whitespace
      -   id: end-of-file-fixer
      -   id: check-yaml
      -   id: debug-statements
      -   id: requirements-txt-fixer

  -   repo: https://github.com/asottile/setup-cfg-fmt
      rev: v2.8.0
      hooks:
      -   id: setup-cfg-fmt

  -   repo: https://github.com/asottile/reorder-python-imports
      rev: v3.15.0
      hooks:
      -   id: reorder-python-imports
          args: [--py39-plus, --add-import, 'from __future__ import annotations']

  -   repo: https://github.com/asottile/add-trailing-comma
      rev: v3.2.0
      hooks:
      -   id: add-trailing-comma

  -   repo: https://github.com/asottile/pyupgrade
      rev: v3.20.0
      hooks:
      -   id: pyupgrade
          args: [--py39-plus]

  -   repo: https://github.com/hhatto/autopep8
      rev: v2.3.2
      hooks:
      -   id: autopep8
  -   repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.17.1
      hooks:
      -   id: mypy

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-docstrings]
